spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssg_db?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username: ssg
    password: ssgpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update